project_name: fireside
builds:
  - 
    main: ./cmd/web
    ldflags: -s -w -X main.buildTime={{ .Date }} -X main.version={{ .Version }}+{{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64
archives:
  - id: tars
    replacements:
      arm64: arm64v6
    format: tar.gz
    files:
      - ui/
      - LICENSE*
      - README*
      - src: './configs/env.example'
        dst: './'
        strip_parent: true
  - id: zips
    replacements:
      arm64: arm64v6
    format: zip
    files:
      - ui/
      - LICENSE*
      - README*
      - src: './configs/env.example'
        dst: './'
        strip_parent: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
